# Generated by Django 3.2.5 on 2021-09-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
