# Generated by Django 3.2.5 on 2021-09-19 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0005_esample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='esample',
        ),
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
