# Generated by Django 3.2.5 on 2021-10-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0009_alter_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='sample2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('file', models.CharField(max_length=40)),
            ],
        ),
    ]
