# Generated by Django 3.2.5 on 2021-10-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0010_sample2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample2',
            old_name='file',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='sample2',
            old_name='text',
            new_name='image_name',
        ),
    ]
