# Generated by Django 3.2.5 on 2021-10-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0011_auto_20211005_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample2',
            old_name='file_name',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='sample2',
            old_name='image_name',
            new_name='imagename',
        ),
    ]
