# Generated by Django 3.2.5 on 2021-10-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0012_auto_20211005_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='sample3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
            ],
        ),
    ]
